name = "tracker-api"
compatibility_date = "2024-08-20"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "USER_TRACKING"
id = "e270556bc3624bc197c1c95bfac14866"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"